# Generated by Django 6.1 on 2026-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
