# Generated by Django 6.1 on 2026-09-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0003_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Student eligibility requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_process',
            field=models.TextField(blank=True, help_text='Example: Technical Round + HR Interview'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'On Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Job requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Required technical skills'),
        ),
    ]
