# Generated by Django 6.1 on 2026-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0005_resumeanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='score',
            new_name='resume_score',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='created_at',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
