# Generated by Django 6.1 on 2026-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0006_rename_score_resumeanalysis_resume_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_score',
            field=models.IntegerField(default=0),
        ),
    ]
