# Generated by Django 6.1 on 2026-09-02 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0007_resume_ai_analysis_resume_extracted_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analyzed_at',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='missing_information',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
