# Generated by Django 6.1 on 2026-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0010_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='direct_apply_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
