# Generated by Django 6.1 on 2026-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0012_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('policy', 'Placement Policy'), ('faq', 'FAQ'), ('company', 'Company Information'), ('job', 'Job Information'), ('procedure', 'Placement Procedure'), ('guideline', 'Student Guideline'), ('interview', 'Interview Instructions'), ('resume', 'Resume Guidelines'), ('career', 'Career Resource')], default='faq', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
