# Generated by Django 6.1 on 2026-09-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0013_knowledgebaseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eligible_departments',
            field=models.CharField(blank=True, help_text='Comma-separated departments, blank = all', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_graduation_years',
            field=models.CharField(blank=True, help_text='Comma-separated graduation years, blank = any', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_backlogs',
            field=models.IntegerField(blank=True, help_text='Maximum allowed active backlogs, blank = no limit', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_cgpa',
            field=models.FloatField(blank=True, help_text='Minimum CGPA (out of 10) required', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_percentage',
            field=models.FloatField(blank=True, help_text='Minimum 10th/12th percentage required', null=True),
        ),
    ]
