# Generated by Django 6.1 on 2026-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0014_job_eligible_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recruiter_notes',
            field=models.TextField(blank=True, help_text='Private notes visible only to the hiring company'),
        ),
    ]
