# Generated by Django 6.1 on 2026-09-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0015_application_recruiter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_drives', to='jobsystem.job'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Online meeting link, if the drive is virtual'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='selection_process',
            field=models.CharField(blank=True, help_text='e.g. Aptitude Test, Technical Interview, HR Interview', max_length=255),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
