# Generated by Django 6.1 on 2026-09-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0017_department_jobcategory_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Query'), ('interview_request', 'Interview Slot Request'), ('application', 'Application Query'), ('resume', 'Resume Query'), ('technical', 'Technical Issue')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('source', models.CharField(default='chatbot', help_text='Where this query came from (chatbot, form, etc.)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsystem.application')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_queries', to='jobsystem.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Placement queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
