# Generated by Django 6.1 on 2026-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0018_placementquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vetri Jobs', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Career Portal', max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Shown in the navbar/sidebar across the whole site instead of the default text badge.', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
