# Generated by Django 6.1 on 2026-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0019_sitebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='login_headline',
            field=models.CharField(blank=True, default='Learn Apply Grow', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='login_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Student Login page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='login_subheadline',
            field=models.CharField(blank=True, default='AI-powered placement platform connecting students with top opportunities.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='register_headline',
            field=models.CharField(blank=True, default='Your Future Starts Here', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='register_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Student Register page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='register_subheadline',
            field=models.CharField(blank=True, default='Join thousands of students and discover your dream career.', max_length=200),
        ),
    ]
