# Generated by Django 6.1 on 2026-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0020_sitebranding_login_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='company_login_headline',
            field=models.CharField(blank=True, default='Hire Top Talent Build Tomorrow', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='company_login_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Company Login page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='company_login_subheadline',
            field=models.CharField(blank=True, default='Connect with skilled students and grow your team.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='company_register_headline',
            field=models.CharField(blank=True, default="Let's Build a Better Tomorrow", max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='company_register_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Company Register page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='company_register_subheadline',
            field=models.CharField(blank=True, default='Create your company account and start hiring the right talent.', max_length=200),
        ),
    ]
