# Generated by Django 6.1 on 2026-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0021_sitebranding_company_login_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='admin_login_headline',
            field=models.CharField(blank=True, default='Complete Control Total Visibility', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='admin_login_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Super Admin Login page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='admin_login_subheadline',
            field=models.CharField(blank=True, default='Manage every user, role and setting across the whole platform.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='placement_login_headline',
            field=models.CharField(blank=True, default='Manage Placements Create Impact', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='placement_login_hero_image',
            field=models.ImageField(blank=True, help_text='Left-panel image on the Placement Admin Login page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='placement_login_subheadline',
            field=models.CharField(blank=True, default='Streamline drives, track progress and empower student success.', max_length=200),
        ),
    ]
