# Generated by Django 6.1 on 2026-09-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0022_sitebranding_admin_login_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('registration_confirmation', 'Registration Confirmation'), ('profile_verification', 'Profile Verification'), ('new_job_alert', 'New Job Alert'), ('application_confirmation', 'Application Confirmation'), ('shortlisted', 'Shortlist Notification'), ('interview_scheduled', 'Interview Schedule'), ('interview_reminder', 'Interview Reminder'), ('selected', 'Selection Notification'), ('rejected', 'Rejection Notification'), ('drive_reminder', 'Placement Drive Reminder')], max_length=40, unique=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Channel Setting',
                'verbose_name_plural': 'Notification Channel Settings',
                'ordering': ['event_key'],
            },
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='chatbot_avatar_image',
            field=models.ImageField(blank=True, help_text='Avatar shown on the floating AI chatbot button and its header, site-wide. Falls back to a robot icon.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='dashboard_assistant_image',
            field=models.ImageField(blank=True, help_text='Illustration shown in the AI Career Assistant card on the Student Dashboard.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='profile_hero_image',
            field=models.ImageField(blank=True, help_text='Illustration shown on the Student Profile page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='verify_token',
            field=models.CharField(default='vetrijobs', help_text="Set this exact value as the 'Verify Token' when configuring the webhook in Meta's WhatsApp Business Platform dashboard.", max_length=100),
        ),
    ]
