# Generated by Django 6.1 on 2026-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0023_notificationchannelsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(blank=True, help_text='e.g. Startup, MNC, SME, Government', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hr_contact_name',
            field=models.CharField(blank=True, help_text='Name of the HR/recruiting contact person.', max_length=150),
        ),
    ]
