# Generated by Django 6.1 on 2026-09-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0026_reportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="Company cannot log in until this is 'approved'.", max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to the company if their application is rejected.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='company/documents/registration/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='gst_document',
            field=models.FileField(blank=True, null=True, upload_to='company/documents/gst/'),
        ),
        migrations.CreateModel(
            name='CompanyRegistrationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='company/documents/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_photos', to='jobsystem.companyprofile')),
            ],
        ),
    ]