# Generated by Django 6.1 on 2026-09-07 11:51
#
# NOTE: this migration originally duplicated every field that
# 0028_homepage_branding.py already adds to SiteBranding (both were
# generated minutes apart against the same parent migration, likely
# from running makemigrations twice). Kept as a no-op instead of
# deleted, since 0029_passwordresetotp.py depends on this migration
# by name - removing the file would break that reference. The actual
# field additions all happen in 0028_homepage_branding.py.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0027_company_approval_workflow'),
    ]

    operations = [
    ]
