# Generated by Django 6.1 on 2026-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0027_company_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_badge_text',
            field=models.CharField(blank=True, default='AI Powered Placement Portal', help_text='Small pill label above the homepage headline.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_headline',
            field=models.CharField(blank=True, default='Smarter Careers', help_text='First line of the homepage headline (default color).', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_headline_highlight',
            field=models.CharField(blank=True, default='Start Here', help_text='Second line of the homepage headline, shown in the accent color.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_subtext',
            field=models.TextField(blank=True, default='Find internships, jobs and placement opportunities with the power of AI. Get personalized job matches, resume insights and interview preparation - all in one platform.', help_text='Paragraph shown under the homepage headline.'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_hero_image',
            field=models.ImageField(blank=True, help_text='Illustration shown on the right of the homepage headline.', null=True, upload_to='branding/'),
        ),
    ]