# Generated by Django 6.1 on 2026-09-07 10:00
#
# NOTE: made a no-op. An earlier deploy attempt got far enough to
# apply this migration's AddField operations against the production
# (Neon) database before a later step in that same deploy failed,
# so these 5 columns already exist on jobsystem_sitebranding in
# production even though this migration wasn't recorded as applied.
# Re-running the AddFields here would fail with "column already
# exists". Leaving this as a no-op instead of deleting it, since
# 0033_merge_20260909_1909.py depends on this migration by name.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0027_company_approval_workflow'),
    ]

    operations = [
    ]
