# Generated by Django 6.1 on 2026-09-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0028_homepage_branding'),
        ('jobsystem', '0032_application_under_review_event'),
    ]

    operations = [
    ]
