# Generated by Django 6.1 on 2026-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsystem', '0033_merge_20260909_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placement_status',
            field=models.CharField(choices=[('Looking', 'Looking'), ('Placed', 'Placed'), ('Not Placed', 'Not Placed')], default='Looking', max_length=20),
        ),
    ]
